### ISSUE TITLE
Export as image function not working when saving with image

### ISSUE THREAD

**Issue by dilushan** [Krapi0314/yorkie-tldraw#6]
When there is a image in the whiteboard and if exported as a image then that downloaded image file contains placeholders for the image

**Comment by krapie** [comment]
OK, it's seems this issue is releated to tldraw itself. You might need to issue this in tldraw github repository too.
I'll check for more details and try to fix this issue ASAP, thank you!

**Comment by ddilushan** [comment]
but its not happening in https://www.tldraw.com/
There official demo site

**Comment by krapie** [comment]
did you tried with multiplayer version of offical tldraw?
I'll give you the link for tldraw multiplayer project that you can test it for.

https://www.tldraw.com/r/1670563077657

**Comment by dilushan** [comment]
ok. it doesn't work in multiplayer. You are right

**Comment by krapie** [comment]
I issued this bug in tldraw: https://github.com/tldraw/tldraw-v1/issues/66
And this issue is resolved: https://github.com/tldraw/tldraw/pull/1130
